# Generated by Django 3.0.5 on 2020-04-14 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('businessId', models.CharField(max_length=200)),
                ('registrationDate', models.DateTimeField(verbose_name='registration date')),
                ('companyForm', models.CharField(max_length=200)),
                ('detailsUri', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
    ]
